@startuml
|#pink|客户|
start

|#lightgray|三只松鼠平台|
#lightgray:**选择订单**;

|分行平台|

|总行|
'-> 订单信息;
' #palegreen:订单结果查询服务;
'
'|三只松鼠平台|
'-> 订单状态信息;
'if(全部订单状态是否正常) then (否)
'    stop
'else (是)
'    :收集融资要素;
'endif
'
'
'|总行|
'-> 融资要求;
':合作方经营快贷款办理查询教研服务;
'
'
'|三只松鼠平台|
'if(是否校验通过) then (否)
'    stop;
'else (是)
'
'|总行|
':个人经营性贷款合同文本查询服务;
'endif
'
'|三只松鼠平台|
':展示合同文本;
'
'|客户|
':签署合同;
'
'|总行|
'-> 完成验签后;
':经营快贷业务影像推送文件API服务;
'stop
'
'|三只松鼠平台|
'start
'
'|总行|
'-> 推送影像资料后;
':合作方个人经营快贷申请服务;
'if(提款是否成功) then (是)
'    :放款;
'else (否)
'    stop
'endif;
end;

@enduml
